### ISSUE TITLE
'trim' function performs two invocations to 'replace' when it could get away with just one

### ISSUE THREAD

**Issue by fedeazzato** [genexuslabs/web-standard-functions#2]
https://github.com/genexuslabs/web-standard-functions/blob/cb506e6549aa6da0730239aa9068777a8fcd8cf8/src/text/trim.ts#L5

Could be written as

```js
return s.replace(/^ +| +$/g,'');
```

**Comment by ncardeli** [comment]
Good catch!

I'd recommend to take a look at `ltrim` and `rtrim` functions as well, as the sould use `+` insted of `*` in the regular expression. The regular expressions could be declared outside of the functions too, to avoid compiling them every time the function is called.

@dmendez could you address these issues please?
